---
kind: pipeline
type: kubernetes
name: default

trigger:
  event: 
    - tag

steps:
  - name: build
    image: plugins/docker
    settings:
      tags:
        - ${DRONE_TAG}
        - latest
      repo: sysr9/gomobile-builder
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password


---
kind: secret
name: docker_username
get:
  path: kv/data/ops/dockerhub
  name: username

---
kind: secret
name: docker_password
get:
  path: kv/data/ops/dockerhub
  name: token
